name: fiscal_noir
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Arquitetura & DI ---
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  equatable: ^2.0.5
  fpdart: ^1.1.0

  # --- Rede & Dados ---
  dio: ^5.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # --- Firebase ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # --- UI & Design ---
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  gap: ^3.0.0
  fl_chart: ^0.66.0
  sentry_flutter: ^7.14.0

  # --- Hardware & Intelligence ---
  camerawesome: ^2.0.0
  google_mlkit_text_recognition: ^0.11.0
  image_editor: ^1.3.0
  path_provider: ^2.1.1

  # --- Utils ---
  uuid: ^4.2.1
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Geradores de CÃ³digo ---
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  package_info_plus: ^8.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
